name: my-pack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
    - name: Pack 
      run: |
        cd Octokit
        dotnet pack -c Release -o ./dist/ -p:version=0.50.1
        dotnet nuget add source --username jxnkwlp --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/jxnkwlp/index.json"
        dotnet nuget push "./dist/Octokit.0.50.1.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
